version: '2'
services:
  mysql:
    image: mysql:latest
    env_file: .env
    volumes:
    - ./db/mysql/dev:/var/lib/mysql
    ports:
    - '3307:3306'
  web:
    build: .
    env_file: .env
    volumes:
    - .:/app
    ports:
    - '3001:3000'
    depends_on:
    - mysql
  mysql_test:
    image: mysql:latest
    env_file: .env.test
    volumes:
    - ./db/mysql/test:/var/lib/mysql
    ports:
    - '3308:3306'