default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_DB_HOST'] %>
  port: <%= ENV['MYSQL_DB_PORT'] %>

production:
  <<: *default
development:
  <<: *default
test:
  <<: *default
